### ISSUE TITLE
Certain primer pairs won't work on similar genomes

### ISSUE THREAD

**Issue by DrownedMala** [treangenlab/Olivar#13]
Hello dear developers,
I am writing to ask you for some advice regarding the usage of your tool.

As of today, I've run a few tests on different viral genomes to test the tool, but I've always bumped into this "problem":
pools prepared on a reference (or genome of choice) perform pretty well (at least [in silico](https://github.com/egonozer/in_silico_pcr)) against very similar genomes, but as soon as a portion of the genome on which a primer was designed diverges a bit more it fails to work. It might be a single pair of primers, or a few, but I've seen it happen more than once. For reference, I'm considering genome that are pretty similar, 99% or above.

I guess it's due to how olivar works, but I was wondering if you have any suggestions about methods to get around this "problem", apart from manually inserting degenerations.
Or perhaps, do you plan to add a function to degenate primers?

Thanks a lot in advance, again!
Have a nice day!
Simone

**Comment by mxwang66** [comment]
Hi Simone, 

Sorry for the late reply! Could you describe your problem with a bit more details? Did you include the sequence variation into the variation list? Could you send me your output files (design csv file and html plots) if possible?

Michael

**Comment by DrownedMala** [comment]
Hi again, sorry for the late reply on my side this time! 
To give more context, I am trying to build the tiled primers for a tri-segmented virus. I am focusing on the smaller sequence of ~900bp, for now, to understand how to surpass this "stall", but I would like to build primers for all three segments together, since you kindly implemented such possibility :)

I'll try to be more clear, proceeding step by the step:

1 - I downloaded sequences of interest from NCBI nt, considering only "same-length" ones, to avoid big gaps at the extremities.
2 - I've run them through parSNP, with mafft as aligner, and outputting a vcf of the MSA.
3 - Converted such VCF into a variant file as per your indications, like the following:
`vcftools --freq --vcf parsnp.vcf`
`awk '{OFS=","} {print $2,$2,$5,$6}' out.frq | awk -F'[,:]' '{OFS=","} {print $1,$2,$4,$3,$5}' > out_freq.csv`
4 - Built the olivar refs passing `the official reference of the organism + out_freq.csv + blast_db_background`; where the blast db used was one built on the t2t genome.
5 - Exploited the tiling function, like this:
`olivar tiling --output "$out" --max-amp-len "$max" --min-amp-len "$min" --temperature "$temp" --seed 10 --threads "$thr" --title "$title" "$ref"`.

Everything went smoothly until now.

6 - To check for the primers to work, I used [in silico PCR](https://github.com/egonozer/in_silico_pcr), like follows:
`./in_silico_PCR.pl -p in_silico_primers.tsv -l <max length previously given to olivar> -m -s <sequence2test>`

When I check against the reference file that I used to build the olvr ref, it works flawlessly. Once I start testing against other sequences (which were used to build the variation file), couples of primers stop working.

Then, today actually, I had the idea to check the web-based version of the tool, where I noticed that the option corresponding to `--check-var` is enabled by default.
Therefore, I tried including such option, but had no significant better results.

Let me know how I can be more exhaustive,
Simone

**Comment by mxwang66** [comment]
Hi @DrownedMala, 

The frequency in the variant file can be understood as mutation frequency, so having a higher frequency means that position is more likely being avoided by primers. 

The steps you listed here totally make sense to me. The reason of some primers stop working for sequences other than the reference, I guess it's because those primers are not perfectly matched to the sequences (e.g., if you use Primer3Plus to check an existing primer against a sequence, it will raise an error if they are not matched perfectly). Could you share a screenshot of the HTML output where primers and variation frequencies are shown? If the variantion density is high, it would be impractical to avoid all of them (but you mentioned you sequences have >99% similarity though). 

Meanwhile in the next update Olivar will support direct input of sequences, it will then perform MSA and variant call so the variation list is no longer neccessary. And we'll also upgrade the validation module to show primer sensitivity (e.g., alignment to input sequences). 

Thanks, 
Michael

**Comment by DrownedMala** [comment]
Well, then I misinterpreted the whole frequency meaning until now!
Anyway, I tried again with the script you passed in issue #12 and it didn't change that much.

From the last time I wrote, I included sequences that are more divergent from the reference (up to 7%), aiming for a comprehensive panel of amplicons that could potentially cover multiple "populations".
After trying with your script to get the frequencies and building an olivar ref from zero, I did retry to build tiling amplicons.
Here is the screen from HTML (in which I cannot see the primers anymore by the way): 
![olivar](https://github.com/user-attachments/assets/ee947abc-cb69-446e-be6e-5876a8c194c6)



For what I've seen testing these latest primers with in_silico_PCR.pl, the general trend seems to be that up to ~5% divergence the primers do work ok, but after that one or two couples (out of 3) usually stop working. 
Even though, when I tested the most divergent sequence, they seemed to work just fine ^-^

Now, I was thinking of re-trying excluding the most similar sequences (to the reference), like > 99% and avoiding the inclusion of sequencese that share a 100% match between them. In my head it might help with rendering the frequency scores a bit more of impact, but I might be wrong.

Cheers,
Simone

**Comment by mxwang66** [comment]
Hi Simone, 

Thanks for the updates! Yeah excluding the most similar sequences makes sense to me. 

From the html screenshot I can see the density of SNPs is pretty high, so it makes sense that some primers might stop working on divergent sequences. But it's weird that the primers disappeared from the plot. Did you change the weights (e.g., `--w-var`) for `olivar tiling`? This might be a bug. 

For the script for making the MSA and variant calling, I have an updated version in this [repo](https://github.com/mxwang66/olivar-validate). It can also plot & validate primer against the MSA, and ambiguous bases are supported. Support for ambiguous bases in the primer design is the next major update for Olivar, since mismatches cannot be completely avoided when mutation density is high. 

Best, 
Michael

**Comment by DrownedMala** [comment]
> Did you change the weights (e.g., --w-var) for olivar tiling? 

No, I've run olivar with default weights for now, only modifying the temperature, at times.

Regarding the updated script for MSA + VCF in the repo "olivar_validate", I can't seem to find it.
I tried the `validate.py` passing the MSA I produced with your previous script and primers produced via `tiling`, which returns me a nice plot of the nucleotide (and primers) distribution and a consensus sequence with no ambiguous bases.
Let me know if I'm looking in the wrong place!

Cheers,
Simone

**Comment by mxwang66** [comment]
@DrownedMala Sorry I forgot to include a wrapper for variant calling ([updated repo](https://github.com/mxwang66/olivar-validate))! Now you can run 
```
validate.py snps MSA.fasta
```
to output the consensus and a list of variations. We are working on merging these features into Olivar. 

I'm not sure why you cannot see the primers in the html plot. I'm sure you tried to zoom in? Perhaps we need a new issue for this bug. 

Michael
