### ISSUE TITLE
How much memory in computer is used to run the software?

### ISSUE THREAD

**Issue by adamiit** [treangenlab/Olivar#18]
![image](https://github.com/user-attachments/assets/b272c3a8-1bea-4202-b1e9-bece8e95ac99)

subprocess to run this command. there is a error, memory out.

**Comment by mxwang66** [comment]
Hi @adamiit , is this the error message output by Olivar? Which command did you run? Please provide more details about how to reproduce this error.

**Comment by adamiit** [comment]
I tried to resolve this problem #8. I found  the problem is caused by that, the BLAST_result.tsv is not created. The error is occured in the ncbi_tools.py line 109. 
![image](https://github.com/user-attachments/assets/78a004f2-d455-4f6a-ae2f-fa21329b42df)

![image](https://github.com/user-attachments/assets/6735def2-4349-44fc-bce2-20355c27018b)

**Comment by mxwang66** [comment]
Could you copy the full error message of Olivar?

**Comment by adamiit** [comment]
![image](https://github.com/user-attachments/assets/28973cfb-c75f-4557-9900-28ace01c4ea4)

**Comment by mxwang66** [comment]
Seems like you are running Olivar directly inside `main.py`. It should be installed as a python package first and then used either from the terminal or imported in python (please check the [installation guide](https://github.com/treangenlab/Olivar#install-with-bioconda-linux-x64-or-mac-intel-chip)). Let me know if you run into error running the example files after installation. 

Also seems like you changed the content in [ncbi_tools.py](url), since the line number does not match to the file in this repo. 

Michael

**Comment by adamiit** [comment]
Yes. I changed the code. Because I occured the problem, which is showed  in the above message. I changed the code, beacuse I want to know the subprocess is normally ran or not. Then I found the subprocess didn't sucessfully run the command "blastn -query .......". So the  "BLAST_result.tsv" is not generated.

**Comment by mxwang66** [comment]
Thanks for the update. Could you check the size of the BLAST database in your cloned repo? It might be because you don't have [git lfs](https://git-lfs.com/) so the database is not cloned correctly.

**Comment by mxwang66** [comment]
Just tried without git-lfs, and it did produce the error in your first message. I'll add a warning in the README to prevent further confusion. Thanks for finding this issue!
