### ISSUE TITLE
The progress bar remains at 0% without any changes.

### ISSUE THREAD

**Issue by wangzhichao1990** [treangenlab/Olivar#21]
Hi, 
I run olivar on Bordetella pertussis genome. However, The progress bar remains at 0% without any changes.
![image](https://github.com/user-attachments/assets/394289ad-b24a-4a8e-8dcb-0f39c60e9422)

Is this software suitable for bacterial genomes? Will the genome be too large to make this plan applicable.

**Comment by mxwang66** [comment]
Hi @wangzhichao1990 , thanks for reaching out! Based on your inputs you would expect ~1000 amplicons, and that well exceeds the limit of regular multiplex PCR. So you might need to trim down your input sequence. 

For the progress bar sticking at 0, most likely it's because there are too many amplicons to design. You can try adding more threads and wait for a longer time. It will only increase by 10% each time. You may also add "nohup" to the start of your command so you won't have to keep the shell session running. 

Let me know if you have any questions! 

Michael

**Comment by wangzhichao1990** [comment]
Thanks for your reply. 
I run in tmux window.
Maybe I should use probes to capture large genomes.
