### ISSUE TITLE
Any recommended upper limit for size of genome(s)?

### ISSUE THREAD

**Issue by tslaird** [treangenlab/Olivar#24]
I was wondering if there was any upper limit (either computationally or experimentally) in terms of the size of the genome(s) to run olivar on. I'm trying to design a primer set for multiple organisms at once and am wondering if I need to only target portions of each genome.

Thanks,

-Tyler-

**Comment by mxwang66** [comment]
Hi @tslaird , 

There is an experimental limit for the number of amplicons in a multiplex PCR assay, mainly due to primers dimers and non-specific amplifications (we discussed this in [SADDLE](https://www.nature.com/articles/s41467-022-29500-4)). Usually 100-200 amplicons would be a comfort zone, for regular sized amplicons (<400bp) and traditional PCR workflow (e.g., the [ARTIC protocol](https://artic.network/2-protocols.html)). However, this cannot be said for sure. For example you may increase the limit by 1) reduce amplicon size, 2) avoid amplifying repetitive and/or low complexity regions (e.g., non-coding regions in human genome), 3) apply enzymes to digest primer dimers (e.g., AmpliSeq), 4) use nested primers, etc. There isn't a computational limit though, as long as you are willing to wait for longer design time for larger inputs. 

For your case, if you target organisms are viruses then there's a higher chance you can cover them together (Olivar now support designing tiled amplicons for multiple targets). But if you are targeting bacteria or even larger genomes, it's unlikely you can cover the whole genomes without some special tricks. However, targeting portions of each genome is usually a good practice since sequencing whole genomes is costly. We are also developing a tool to find signature regions in whole genomes that serve as good targets, so stay tuned! 

Michael

**Comment by mxwang66** [comment]
@tslaird Selecting regions to be targeted is a trade off between sensitivity and specificity. Sensitivity is the percentage of target genomes that could be amplified, usually hindered by SNPs. Specificity is determined by the amount of amplification on irrelavant genomes. 

Sensitivity can be measure by MSA (multiple sequence alignment). You might find this [tool](https://github.com/mxwang66/olivar-validate) helpful for measuring sensitivity. 

Specificity is usually measure with BLAST. You may run BLAST online or locally against the comprehensive nt database (or your customized db, see [Olivar readme](https://github.com/treangenlab/Olivar?tab=readme-ov-file#prepare-a-blast-database) for more details). To limit search results, you can exclude your targeted genome from the BLAST db. This can be done both online or locally (the `-negative_taxids` option). 

The final question would be how to selected candidate regions. Well for now this is the hard one, and might need some manual work (that's why we are working on a tool to solve this). For viruses, you can make whole genome MSA (e.g., with mafft), visualize it and pick some regions. For bacteria it would be hard to make an end-to-end MSA due to genome size, so I would recommend [Parsnp](https://github.com/marbl/parsnp) to do core genome alignment. However, you can always go to literatures to find which regions/genes are targeted for each organism. But be careful about their application, for example they might use cultured samples and specificity is not an issue, so they might target super conserved regions (we had some painful experience on this one). 

Good luck with your design, 
Michael

**Comment by tslaird** [comment]
Thanks! @mxwang66 

I saw the Influenza A olivar repository (https://github.com/treangenlab/InfA-amplicon) and the difficulty with covering multiple different N1 sequences. Is there an ANI or percent homology threshold you recommend not going below for the tiling to work optimally on homologous genes or viral genomes?

Thanks,

-Tyler-

**Comment by mxwang66** [comment]
>95% ANI I would say, this threshold is also recommended by PrimalScheme
